-- create role
USE ROLE ACCOUNTADMIN;

-- create warehouse

CREATE OR REPLACE WAREHOUSE WH_ECOMMERCE
WITH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE WH_ECOMMERCE;
ALTER WAREHOUSE RESUME;

-- create database
CREATE OR REPLACE DATABASE ECOMMERCE_DB;
USE DATABASE ECOMMERCE_DB;

-- create schema 

CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA STAGING;
CREATE OR REPLACE SCHEMA ANALYTICS;

USE SCHEMA RAW;
USE SCHEMA STAGING;
USE SCHEMA ANALYTICS;

-- create file format for csv file
CREATE OR REPLACE FILE FORMAT ECOMMERCE_CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
TRIM_SPACE = TRUE
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', 'null', '');

--create stage for dataload
CREATE OR REPLACE STAGE ECOMMERCE_RAW_STAGE
FILE_FORMAT = ECOMMERCE_CSV_FORMAT;